Description: "Launch Configuration 
  four servers
  two in each private subnet
  auto-scaling group
  two vCPUs and at least 4GB
  Ubuntu 18
  12GB of disk space."
Parameters:
  KeyName:
    Description: udakey
    Type: String
    MinLength: "1"
    MaxLength: "64"
    AllowedPattern: "[-_ a-zA-Z0-9]*"
    ConstraintDescription: can contain only alphanumeric characters, spaces, dashes and underscores.
  SSHLocation:
    Description: Lockdown SSH access to the bastion host (default can be accessed
      from anywhere)
    Type: String
    MinLength: "9"
    MaxLength: "18"
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid CIDR range of the form x.x.x.x/x.
  FrontendInstanceType:
    Description: Frontend Server EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
  
    ConstraintDescription: must be a valid EC2 instance type.
  FrontendSize:
    Description: Number of EC2 instances to launch for the Frontend server
    Type: Number
    Default: "1"
  BackendInstanceType:
    Description: Backend Server EC2 instance type
    Type: String
    Default: m1.small
    AllowedValues:
      - t2.micro

    ConstraintDescription: must be a valid EC2 instance type.
  BackendSize:
    Description: Number of EC2 instances to launch for the backend server
    Type: Number
    Default: "2"
  BastionInstanceType:
    Description: Bastion Host EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
  
    ConstraintDescription: must be a valid EC2 instance type.

 
Mappings:
  SubnetConfig:
    VPC: !Ref UdaVPC
    Public:
      CIDR: 12.0.0.0/24
    Private:
      CIDR: 12.0.1.0/24


Resources:
  UdaVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 12.0.0.0/16
      Tags:
        - Key: Application
          Value: !Ref AWS::StackId
        - Key: Network
          Value: Public
  
  pubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref UdaVPC
      CidrBlock: !FindInMap
        - SubnetConfig
        - Public
        - CIDR
      Tags:
        - Key: Application
          Value: !Ref AWS::StackId
        - Key: Network
          Value: Public
  
  iWay:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Application
          Value: !Ref AWS::StackId
        - Key: Network
          Value: Public

  gateToNet:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref UdaVPC
      InternetGatewayId: !Ref iWay

  pubTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref UdaVPC
      Tags:
        - Key: Application
          Value: !Ref AWS::StackId
        - Key: Network
          Value: Public

  pubRoute:
    Type: AWS::EC2::Route
    DependsOn: gateToNet
    Properties:
      RouteTableId: !Ref pubTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref iWay

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref pubnet
      RouteTableId: !Ref pubTable

  PublicNetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref UdaVPC
      Tags:
        - Key: Application
          Value: !Ref AWS::StackId
        - Key: Network
          Value: Public

  InboundHTTPPublicNetworkAclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PublicNetworkAcl
      RuleNumber: 100
      Protocol: 6
      RuleAction: allow
      Egress: false
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 80
        To: 80

  InboundHTTPSPublicNetworkAclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PublicNetworkAcl
      RuleNumber: 101
      Protocol: 6
      RuleAction: allow
      Egress: false
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 443
        To: 443

  InboundSSHPublicNetworkAclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref  PublicNetworkAcl
      RuleNumber: 102
      Protocol: 6
      RuleAction: allow
      Egress: false
      CidrBlock: !Ref SSHLocation
      PortRange:
        From: 22
        To: 22

  InboundEmphemeralPublicNetworkAclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PublicNetworkAcl
      RuleNumber: 103
      Protocol: 6
      RuleAction: allow
      Egress: false
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 1024
        To: 65535

  OutboundPublicNetworkAclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PublicNetworkAcl
      RuleNumber: 100
      Protocol: 6
      RuleAction: allow
      Egress: true
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 0
        To: 65535

  PublicSubnetNetworkAclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId: !Ref pubnet
      NetworkAclId: !Ref PublicNetworkAcl

  priSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref UdaVPC
      CidrBlock: !FindInMap
        - SubnetConfig
        - Private
        - CIDR
      Tags:
        - Key: Application
          Value: !Ref AWS::StackId
        - Key: Network
          Value: Private

  PriTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref UdaVPC
      Tags:
        - Key: Application
          Value: !Ref AWS::StackId
        - Key: Network
          Value: Private

  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref priSubnet
      RouteTableId: !Ref PriTable

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PriTable
      DestinationCidrBlock: 0.0.0.0/0
      InstanceId: !Ref NATGate

  PrivateNetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref UdaVPC
      Tags:
        - Key: Application
          Value: !Ref AWS::StackId
        - Key: Network
          Value: Private

  InboundPrivateNetworkAclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PrivateNetworkAcl
      RuleNumber: 100
      Protocol: 6
      RuleAction: allow
      Egress: false
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 0
        To: 65535

  OutBoundPrivateNetworkAclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PrivateNetworkAcl
      RuleNumber: 100
      Protocol: 6
      RuleAction: allow
      Egress: true
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 0
        To: 65535

  PrivateSubnetNetworkAclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId: !Ref priSubnet
      NetworkAclId: !Ref PrivateNetworkAcl

  NATIPAddress:
    Type: AWS::EC2::EIP
    DependsOn: gateToNet
    Properties:
      Domain: vpc
      InstanceId: !Ref NATGate
  
  NATGate:
    Type: AWS::EC2::NatGateway
    Properties: 
      AllocationId: !Ref NATIPAddress
      ConnectivityType: public
      SubnetId: !Ref pubnet
      Tags: 
          - Tag

  BastionIPAddress:
    Type: AWS::EC2::EIP
    DependsOn: gateToNet
    Properties:
      Domain: vpc
      InstanceId: !Ref BastionHost
      
  BastionHost:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref BastionInstanceType
      KeyName: !Ref KeyName
      SubnetId: !Ref pubnet
      ImageId: !FindInMap
        - AWSRegionArch2AMI
        - !Ref 'AWS::Region'
        - Fn::FindInMap:
            - AWSInstanceType2Arch
            - !Ref 'BastionInstanceType'
            - Arch
      SecurityGroupIds:
        - Ref: BastionSecurityGroup

  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable access to the Bastion host
      VpcId: !Ref UdaVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !FindInMap
            - SubnetConfig
            - Private
            - CIDR
  
  PublicElasticLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      SecurityGroups: !Ref PublicLoadBalancerSecurityGroup
      Subnets: !Ref pubnet
      Listeners:
        - LoadBalancerPort: 80
          InstancePort: 80
          Protocol: HTTP
      HealthCheck:
        Target: HTTP:80/
        HealthyThreshold: 3
        UnhealthyThreshold: 5
        Interval: 90
        Timeout: 60

  PublicLoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Public ELB Security Group with HTTP access on port 80 from the internet
      VpcId: !Ref UdaVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  FrontendFleet:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
        - Fn::GetAtt:
            - priSubnet
            - AvailabilityZone
      VPCZoneIdentifier:
        - Ref: priSubnet
      LaunchConfigurationName: !Ref  FrontendServerLaunchConfig
      MinSize: "1"
      MaxSize: "2"
      DesiredCapacity: !Ref  FrontendSize
      LoadBalancerNames:
        - Ref: PublicElasticLoadBalancer
      Tags:
        - Key: Network
          Value: Public
          PropagateAtLaunch: true
  FrontendServerLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Metadata:
      Comment1: Configure the FrontendServer to forward /backend requests to the
        backend servers
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              httpd: []
          files:
            /var/www/html/index.html:
              content:
                Fn::Join:
                  - "\n"
                  - - <img
                      src="https://s3.amazonaws.com/cloudformation-examples/cloudformation_graphic.png"
                      alt="AWS CloudFormation Logo"/>
                    - <h1>Congratulations, you have successfully launched the
                      multi-tier AWS CloudFormation sample.</h1>
                    - <p>This is a multi-tier web application launched in an
                      Amazon Virtual Private Cloud (Amazon VPC) with multiple
                      subnets. The first subnet is public and contains and
                      internet facing load balancer, a NAT device for internet
                      access from the private subnet and a bastion host to allow
                      SSH access to the hosts in the private subnet. The second
                      subnet is private and contains a Frontend fleet of EC2
                      instances, an internal load balancer and a Backend fleet
                      of EC2 instances.
                    - <p>To serve a web page from the backend service, click <a
                      href="/backend">here</a>.</p>
              mode: "000644"
              owner: root
              group: root
            /etc/httpd/conf.d/maptobackend.conf:
              content:
                Fn::Join:
                  - ""
                  - - ProxyPass /backend http://
                    - Fn::GetAtt:
                        - PrivateElasticLoadBalancer
                        - DNSName
                    - "\n"
                    - ProxyPassReverse /backend http://
                    - Fn::GetAtt:
                        - PrivateElasticLoadBalancer
                        - DNSName
                    - "\n"
              mode: "000644"
              owner: root
              group: root
          services:
            sysvinit:
              httpd:
                enabled: "true"
                ensureRunning: "true"
                files:
                  - /etc/httpd/conf.d/maptobackend.conf
                  - /var/www/html/index.html
    Properties:
      ImageId:
        Fn::FindInMap:
          - AWSRegionArch2AMI
          - Ref: AWS::Region
          - Fn::FindInMap:
              - AWSInstanceType2Arch
              - Ref: FrontendInstanceType
              - Arch
      SecurityGroups:
        - Ref: FrontendSecurityGroup
      InstanceType: !Ref  FrontendInstanceType
      KeyName: !Ref  KeyName
      UserData:
        Fn::Base64:
          Fn::Join:
            - ""
            - - |
                #!/bin/bash -v
              - |
                yum update -y aws-cfn-bootstrap
              - |
                # Install Apache and configure as a reverse Frontend
              - "/opt/aws/bin/cfn-init --stack "
              - Ref: AWS::StackId
              - " --resource FrontendServerLaunchConfig -u
                https://cloudformation.cn-north-1.amazonaws.com.cn"
              - "    --region "
              - Ref: AWS::Region
              - "\n"
              - |
                # Signal completion
              - /opt/aws/bin/cfn-signal -e $? -r "Frontend setup done" '
              - Ref: FrontendWaitHandle
              - |
                '
  FrontendSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access from load balancer and bastion as well as
        outbound HTTP and HTTPS traffic
      VpcId: !Ref UdaVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref PublicLoadBalancerSecurityGroup
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref BastionSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
  FrontendWaitHandle:
    Type: AWS::CloudFormation::WaitConditionHandle
  FrontendWaitCondition:
    Type: AWS::CloudFormation::WaitCondition
    DependsOn: FrontendFleet
    Properties:
      Handle: !Ref  FrontendWaitHandle
      Timeout: 3600
      Count: !Ref  FrontendSize
  PrivateElasticLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      SecurityGroups:
        - Ref: PrivateLoadBalancerSecurityGroup
      Subnets:
        - Ref: priSubnet
      Listeners:
        - LoadBalancerPort: 80
          InstancePort: 80
          Protocol: HTTP
      Scheme: internal
      HealthCheck:
        Target: HTTP:80/
        HealthyThreshold: 3
        UnhealthyThreshold: 5
        Interval: 90
        Timeout: 60
  PrivateLoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Private ELB Security Group with HTTP access on port 80 from
        the Frontend Fleet only
      VpcId: !Ref UdaVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref FrontendSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  BackendFleet:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
        - Fn::GetAtt:
            - priSubnet
            - AvailabilityZone
      VPCZoneIdentifier:
        - Ref: priSubnet
      LaunchConfigurationName: !Ref  BackendLaunchConfig
      MinSize: "1"
      MaxSize: "2"
      DesiredCapacity: !Ref  BackendSize
      LoadBalancerNames:
        - Ref: PrivateElasticLoadBalancer
      Tags:
        - Key: Network
          Value: Private
          PropagateAtLaunch: true

  BackendLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Metadata:
      Comment1: Configure the Backend server to respond to requests
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              httpd: []
          files:
            /var/www/html/index.html:
              content:
                Fn::Join:
                  - "\n"
                  - - <img
                      src="https://s3.amazonaws.com/cloudformation-examples/cloudformation_graphic.png"
                      alt="AWS CloudFormation Logo"/>
                    - <h1>Congratulations, this request was served from the
                      backend fleet</h1>
              mode: "000644"
              owner: root
              group: root
          services:
            sysvinit:
              httpd:
                enabled: "true"
                ensureRunning: "true"
                files:
                  - /var/www/html/index.html
    Properties:
      ImageId:
        Fn::FindInMap:
          - AWSRegionArch2AMI
          - Ref: AWS::Region
          - Fn::FindInMap:
              - AWSInstanceType2Arch
              - Ref: BackendInstanceType
              - Arch
      SecurityGroups:
        - Ref: BackendSecurityGroup
      InstanceType: !Ref  BackendInstanceType
      KeyName: !Ref  KeyName
      UserData:
        Fn::Base64:
          Fn::Join:
            - ""
            - - |
                #!/bin/bash -v
              - |
                yum update -y aws-cfn-bootstrap
              - |
                # Install Apache
              - "/opt/aws/bin/cfn-init --stack "
              - Ref: AWS::StackId
              - " --resource BackendLaunchConfig -u
                https://cloudformation.cn-north-1.amazonaws.com.cn"
              - "    --region "
              - Ref: AWS::Region
              - "\n"
              - |
                # Signal completion
              - /opt/aws/bin/cfn-signal -e $? -r "Backend setup done" '
              - Ref: BackendWaitHandle
              - |
                '
  BackendSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access from private load balancer and bastion as well as
        outbound HTTP and HTTPS traffic
      VpcId: !Ref UdaVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "80"
          ToPort: "80"
          SourceSecurityGroupId: !Ref PrivateLoadBalancerSecurityGroup
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          SourceSecurityGroupId: !Ref BastionSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: "80"
          ToPort: "80"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "443"
          ToPort: "443"
          CidrIp: 0.0.0.0/0

  BackendWaitHandle:
    Type: AWS::CloudFormation::WaitConditionHandle

  BackendWaitCondition:
    Type: AWS::CloudFormation::WaitCondition
    DependsOn: BackendFleet
    Properties:
      Handle: !Ref  BackendWaitHandle
      Timeout: "300"
      Count: !Ref  BackendSize

Outputs:
  WebSite:
    Description: URL of the website
    Value:
      Fn::Join:
        - ""
        - - http://
          - Fn::GetAtt:
              - PublicElasticLoadBalancer
              - DNSName
  Bastion:
    Description: IP Address of the Bastion host
    Value: !Ref BastionIPAddress
